
site_name: C++ 핵심 가이드라인
site_description: "C++ 핵심 가이드라인 한글화 프로젝트"
site_author: C++ Korea
site_url: https://luncliff.github.io/core-guidelines/

repo_name: luncliff/CppCoreGuidelines
repo_url: https://github.com/luncliff/core-guidelines

copyright: "Copyright (c) Standard C++ Foundation and its contributors"


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search:
      lang: 
        - en
        - ko

extra:
  # alternate:
  #   - name: 한국어
  #     link: core-guidelines/ko/
  #     lang: ko
  #   - name: English
  #     link: core-guidelines/en/
  #     lang: en
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/orgs/cppkorea
    - icon: fontawesome/brands/discord
      link: https://discord.gg/87SNegGZue
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/groups/cppkorea
    - icon: fontawesome/solid/paper-plane
      link: mailto:contact@cppkorea.org

theme:
  name: "material"
  language: "ko"
  extra:
    search:
      language: "ko"
  font:
    text: "Nanum Gothic"
    code: "Nanum Gothic Coding"
  icon:
    repo: fontawesome/brands/github
    admonition:
      tip: fontawesome/solid/gears
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny 
        name: Switch to light mode
      primary: "Indigo"
      accent: "blue"
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - content.tabs.link
    - search.suggest
    - search.highlight
    - navigation.path
    - toc.integrate
  logo: "images/logo.svg"

docs_dir: sections
nav:
  - Overview: home.md
  - Introduction: Introduction.md
  - References: References.md
  - Sections:
    - Architecture: Architecture.md
    - Class: Class.md
    - Concurrency: Concurrency.md
    - Const: Const.md
    - C-Style: CPL.md
    - Enum: Enum.md
    - Errors: Errors.md
    - Expr: Expr.md
    - Functions: Functions.md
    - Glossary: Glossary.md
    - GSL: GSL.md
    - Interfaces: Interfaces.md
    - Naming: Naming.md
    - Not-Rule: Not.md
    - Performance: Performance.md
    - Philosophy: Philosophy.md
    - Profile: Profile.md
    - Resource: Resource.md
    - Standard Library: SL.md
    - Source: Source.md
    - Templates: Templates.md
    - Unclassified: Unclassified.md
  - Appendix:
    # - Discussion: appendix/Discussion.md
    # - Libraries: appendix/Libraries.md
    - Modernizing: appendix/Modernizing.md
    - Tools: appendix/Tools.md
