
site_name: C++ 핵심 가이드라인
site_description: "C++ 핵심 가이드라인 한글화 프로젝트"
site_author: C++ Korea
site_url: https://luncliff.github.io/core-guidelines/

repo_name: luncliff/CppCoreGuidelines
repo_url: https://github.com/luncliff/core-guidelines

copyright: "Copyright (c) Standard C++ Foundation and its contributors"


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search:
      lang: 
        - en
        - ko

extra:
  # alternate:
  #   - name: 한국어
  #     link: core-guidelines/ko/
  #     lang: ko
  #   - name: English
  #     link: core-guidelines/en/
  #     lang: en
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/orgs/cppkorea
    - icon: fontawesome/brands/discord
      link: https://discord.gg/87SNegGZue
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/groups/cppkorea
    - icon: fontawesome/solid/paper-plane
      link: mailto:contact@cppkorea.org

theme:
  name: "material"
  language: "ko"
  extra:
    search:
      language: "ko"
  font:
    text: "Nanum Gothic"
    code: "Nanum Gothic Coding"
  icon:
    repo: fontawesome/brands/github
    admonition:
      tip: fontawesome/solid/gears
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny 
        name: Switch to light mode
      primary: "Indigo"
      accent: "blue"
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - content.tabs.link
    - search.suggest
    - search.highlight
    - navigation.path
    - toc.integrate
  logo: "images/logo.svg"

docs_dir: sections
nav:
  - Overview: home.md
  - Introduction: Introduction.md
  - References: References.md
  - Sections:
    - Architecture: Architecture.md
    - Class: Class.md
    - Concurrency: Concurrency.md
    - Const: Const.md
    - C-Style: CPL.md
    - Enum: Enum.md
    - Errors: Errors.md
    - Expr: Expr.md
    - Functions: Functions.md
    - Glossary: Glossary.md
    - GSL: GSL.md
    - Interfaces: Interfaces.md
    - Naming: Naming.md
    - Not-Rule: Not.md
    - Performance: Performance.md
    - Philosophy: Philosophy.md
    - Profile: Profile.md
    - Resource: Resource.md
    - Standard Library: SL.md
    - Source: Source.md
    - Templates: Templates.md
    - Unclassified: Unclassified.md
  - Appendix:
    # - Discussion: appendix/Discussion.md
    # - Libraries: appendix/Libraries.md
    - Modernizing: appendix/Modernizing.md
    - Tools: appendix/Tools.md
  - Untranslated:
    - In : en/In_-Introduction.md
    - In.target : en/In-target_-Target-readership.md
    - In.aims : en/In-aims_-Aims.md
    - In.not : en/In-not_-Non-aims.md
    - In.force : en/In-force_-Enforcement.md
    - In.struct : en/In-struct_-The-structure-of-this-document.md
    - In.sec : en/In-sec_-Major-sections.md
    - P : en/P_-Philosophy.md
    - I : en/I_-Interfaces.md
    - F : en/F_-Functions.md
    - F.def : en/F-def_-Function-definitions.md
    - F.call : en/F-call_-Parameter-passing.md
    - C : en/C_-Classes-and-class-hierarchies.md
    - C.concrete : en/C-concrete_-Concrete-types.md
    - C.ctor : en/C-ctor_-Constructors-assignments-and-destructors.md
    - C.defop : en/C-defop_-Default-Operations.md
    - C.dtor : en/C-dtor_-Destructors.md
    - C.ctor : en/C-ctor_-Constructors.md
    - C.copy : en/C-copy_-Copy-and-move.md
    - C.other : en/C-other_-Other-default-operation-rules.md
    - C.con : en/C-con_-Containers-and-other-resource-handles.md
    - C.lambdas : en/C-lambdas_-Function-objects-and-lambdas.md
    - C.hier : en/C-hier_-Class-hierarchies-OOP.md
    - C.hierclass : en/C-hierclass_-Designing-classes-in-a-hierarchy_.md
    - C.hier-access : en/C-hier-access_-Accessing-objects-in-a-hierarchy.md
    - C.over : en/C-over_-Overloading-and-overloaded-operators.md
    - C.union : en/C-union_-Unions.md
    - Enum : en/Enum_-Enumerations.md
    - R : en/R_-Resource-management.md
    - R.alloc : en/R-alloc_-Allocation-and-deallocation.md
    - R.smart : en/R-smart_-Smart-pointers.md
    - ES : en/ES_-Expressions-and-statements.md
    - ES.dcl : en/ES-dcl_-Declarations.md
    - ES.expr : en/ES-expr_-Expressions.md
    - ES.stmt : en/ES-stmt_-Statements.md
    - Per : en/Per_-Performance.md
    - CP : en/CP_-Concurrency-and-parallelism.md
    - CP.con : en/CP-con_-Concurrency.md
    - CP.coro : en/CP-coro_-Coroutines.md
    - CP.par : en/CP-par_-Parallelism.md
    - CP.mess : en/CP-mess_-Message-passing.md
    - CP.vec : en/CP-vec_-Vectorization.md
    - CP.free : en/CP-free_-Lock-free-programming.md
    - CP.etc : en/CP-etc_-Etc--concurrency-rules.md
    - E : en/E_-Error-handling.md
    - Con : en/Con_-Constants-and-immutability.md
    - T : en/T_-Templates-and-generic-programming.md
    - T.gp : en/T-gp_-Generic-programming.md
    - T.concepts : en/T-concepts_-Concept-rules.md
    - T.con-use : en/T-con-use_-Concept-use.md
    - T.concepts.def : en/T-concepts-def_-Concept-definition-rules.md
    - T.def : en/T-def_-Template-definitions.md
    - T.temp-hier : en/T-temp-hier_-Template-and-hierarchy-rules_.md
    - T.var : en/T-var_-Variadic-template-rules.md
    - T.meta : en/T-meta_-Template-metaprogramming-TMP.md
    - CPL : en/CPL_-C-style-programming.md
    - SF : en/SF_-Source-files.md
    - SL : en/SL_-The-Standard-Library.md
    - SL.con : en/SL-con_-Containers.md
    - SL.str : en/SL-str_-String.md
    - SL.io : en/SL-io_-Iostream.md
    - SL.regex : en/SL-regex_-Regex.md
    - SL.chrono : en/SL-chrono_-Time.md
    - SL.C : en/SL-C_-The-C-Standard-Library.md
    - A : en/A_-Architectural-ideas.md
    - NR : en/NR_-Non-Rules-and-myths.md
    - RF : en/RF_-References.md
    - RF.rules : en/RF-rules_-Coding-rules.md
    - RF.books : en/RF-books_-Books-with-coding-guidelines.md
    - RF.C++ : en/RF-C++_-C++-Programming-C++11-C++14.md
    - RF.web : en/RF-web_-Websites.md
    - RS.video : en/RS-video_-Videos-about-modern-C++.md
    - RF.man : en/RF-man_-Manuals.md
    - RF.core : en/RF-core_-Core-Guidelines-materials.md
    - Pro : en/Pro_-Profiles.md
    - Pro.safety : en/Pro-safety_-Type-safety-profile.md
    - Pro.bounds : en/Pro-bounds_-Bounds-safety-profile.md
    - Pro.lifetime : en/Pro-lifetime_-Lifetime-safety-profile.md
    - GSL : en/GSL_-Guidelines-support-library.md
    - GSL.view : en/GSL-view_-Views.md
    - GSL.owner : en/GSL-owner_-Ownership-pointers.md
    - GSL.assert : en/GSL-assert_-Assertions.md
    - GSL.util : en/GSL-util_-Utilities.md
    - GSL.concept : en/GSL-concept_-Concepts.md
    - NL : en/NL_-Naming-and-layout-suggestions.md
    - FAQ : en/FAQ_-Answers-to-frequently-asked-questions.md
    - Appendix A : en/Appendix-A_-Libraries.md
    - Appendix B : en/Appendix-B_-Modernizing-code.md
    - Appendix C : en/Appendix-C_-Discussion.md
    - Appendix D : en/Appendix-D_-Supporting-tools.md
    - To-do : en/To-do_-Unclassified-proto-rules.md
